### ISSUE TITLE
Focusing into a focus zone from detached focus does not use provided `focusInStrategy` function

### ISSUE THREAD

**Issue by iansan5653** [primer/behaviors#64]
NOTE: For lack of a better term here, when I refer to *detached focus* I mean when no specific element is focused but the browsers knows where in the focus flow the user should be. For example, this can happen when the currently focused element is unmounted or disabled, or if the element is the first focuseable item on the page.

When tabbing from a detached focus state to a focus zone that has a `focusInStrategy` function set, the function is not called and thus the first focuseable element in the zone is always focused. This appears to be because the function is only called if `event.relatedTarget instanceof HTMLElement` but there is no `relatedTarget` in this case (`relatedTarget` is `null`). It looks like the check may just be here to satisfy TypeScript:

https://github.com/primer/behaviors/blob/f799310165020e0628f8b165522a3db7f07332b3/src/focus-zone.ts#L585

Here is a minimal demo of an instance where `relatedTarget` can be `null`: https://jsfiddle.net/9cn7zxaq/

Here is an example of an instance where this causes a problem. I am building a datepicker and when I press the "Today" button, it is disabled because the picker moves to today's date. Focus is lost, then if the user <kbd>Shift</kbd>+<kbd>Tab</kbd>s to the days grid, I have a `focusInStrategy` that will set the focus to the correct day. However, my strategy is not called and the focus is set to the first day of the month instead.

https://user-images.githubusercontent.com/2294248/156049558-0945ab3f-db2a-4218-99c6-b37f80481a5e.mov

**Comment by rezrah** [comment]
Hi @iansan5653 - thanks for filing this bug report. We're going to take a closer look at this in the Primer React team over the next week, but unfortunately I can't commit to a resolution date just yet.

At this time, we don't have high confidence that a fix will not create downstream regressions in Primer React. This is because `useFocusZone`, which many components in Primer React rely on does not have adequate test coverage. To avoid these risks, we want to be a bit more cautious with this update.

Our plan is currently:

1. Backfill the test coverage for `useFocusZone` in PRC repo (0 coverage)
2. Backfill test coverage for `focusZone.ts` in this repo (currently <80% coverage)
3. Investigate / remediate reported bug

We're being extra cautious as we've recently seen various ad-hoc bugfixes ship, that created regressions in their dependencies and required rollback. 

**Did you already have a solution in mind for point 3?** If so, please feel free to put a PR up for it, or we can take a look at it once we've resolved the first two points.

**Comment by iansan5653** [comment]
> Did you already have a solution in mind for point 3?

I do, but it is opinionated - I don't know if your team will want to go in the same direction.

In my opinion the best solution would be to just forward the behavior by passing `null` to the callback. This would require a breaking change to the types though - the type of [`focusInStrategy`](https://github.com/primer/behaviors/blob/f799310165020e0628f8b165522a3db7f07332b3/src/focus-zone.ts#L214) would have to change to add `null` to the function arg type:

```diff
- focusInStrategy?: 'first' | 'closest' | 'previous' | ((previousFocusedElement: Element) => HTMLElement | undefined)
+ focusInStrategy?: 'first' | 'closest' | 'previous' | ((previousFocusedElement: Element | null) => HTMLElement | undefined)
```

Anywhere consuming code is providing a function they'll have to handle the `null` case. I think this would be a pretty safe change from a testing perspective on this end since we'd just be forwarding the behavior downstream.
